# Environment params
sim_length: 90 # [days]
# Supported simulations types are:
# - "pricing": runs only the pricing algorithm
# - "bidding": runs only the bidding algorithm
# - "both": runs the full simulation with the algorithms interacting with each other
type: "both"
n_steps_per_day: 10 # Number of auctions/user interactions to run each day.
# Auction params
auction:
  n_opponents_dist:
    # Supported n_opponents distribution types are:
    # - "trunc_normal": normal distribution with (mean, std) truncated between min and max
    # - "constant": constant at mean
    # - "uniform": uniform between min and max
    type: "trunc_normal"
    mean: 10
    std: 3
    min: 0
    max: 20

# Logger
log_path: ".\\src\\logger\\logs\\"