# DEFAULT SETTINGS
defaults: &defaults
  trials: 10
  verbose: true # Whether to save the stats of the trials in a log file
  silent: false # Whether to show the trial progress in the terminal
  seed: 42
  # Supported simulations types are:
  # - "pricing": runs only the pricing algorithm
  # - "bidding": runs only the bidding algorithm
  # - "both": runs the full simulation where the advertisement campaign
  #           (the bidding part) influences how many of the users
  #           actually see the price of the product, and thus decide
  #           whether to buy it or not.
  type: "both"
  users: &users
    # Supported n_opponents distribution types are:
    # - "trunc_normal": normal distribution with (mean, std) truncated 
    #                   between min and max
    # - "constant": constant at mean
    # - "uniform": uniform between min and max
    n_dist:
      type: "constant"
      mean: 5
      std: null
      min: null
      max: null
    # Supported simulations types are:
    # - "random"
    # - "linear" needs alpha and beta
    # - "probit" needs alpha and beta
    # - "logit" needs alpha and beta
    # - "kernel" needs alpha, beta, and gamma
    type: "random"
  # Auction params
  auction: &auction
    type: "random"
    agents:
      - type: "random"
        count: 1
        budget: 50
    opponents: &opponents
      # Supported n_opponents distribution types are:
      # - "trunc_normal": normal distribution with (mean, std) truncated
      #                   between min and max
      # - "constant": constant at mean
      # - "uniform": uniform between min and max
      n_dist:
        type: "constant"
        mean: 10
        std: null
        min: null
        max: null
      type: "random"
  pricing: &pricing
    # TODO implement 2 items pricing
    num_prods: 1
    cost: 0.2
    agent:
      type: "random"

# SETTINGS FOR EACH REQUIREMENT
req_1:
  <<: *defaults
  type: "pricing"
  pricing:
    <<: *pricing
    agent:
      type: "gpucb"
      discretization: 101
  users:
    <<: *users
    type: linear
    alpha: 1
    beta: -1
  auction: 
    <<: *auction
    type: "second_price"
req_2:
  <<: *defaults
  auction:
    <<: *auction
    type: "generalized_first_price"
req_3:
  <<: *defaults
  type: "pricing"
req_3_bonus:
  <<: *defaults
  type: "pricing"
  pricing: 
    <<: *pricing
    num_items: 2
req_4:
  <<: *defaults
  type: "bidding"
  auction:
    <<: *auction
    agents:
      - type: "random"
        count: 4
        budget: 50

# Logger
log_path: ".\\logger\\logs"