# DEFAULT SETTINGS
defaults: &defaults
  sim_length: 90 # [days]
  # Supported simulations types are:
  # - "pricing": runs only the pricing algorithm
  # - "bidding": runs only the bidding algorithm
  # - "both": runs the full simulation with the algorithms interacting with each other
  type: "both"
  users: &users
    # Supported n_opponents distribution types are:
    # - "trunc_normal": normal distribution with (mean, std) truncated between min and max
    # - "constant": constant at mean
    # - "uniform": uniform between min and max
    n_dist:
      type: "constant"
      mean: 10
      std: null
      min: null
      max: null
    # Supported simulations types are:
    # - "random"
    # - "linear" needs alpha and beta
    # - "probit" needs alpha and beta
    # - "logit" needs alpha and beta
    # - "kernel" needs alpha, beta, and gamma
    type: "random"
    alpha: null
    beta: null
    gamma: null
  # Auction params
  auction: &auction
    type: "random"
    agents:
      - type: "random"
        count: 1
    opponents: &opponents
      # Supported n_opponents distribution types are:
      # - "trunc_normal": normal distribution with (mean, std) truncated between min and max
      # - "constant": constant at mean
      # - "uniform": uniform between min and max
      n_dist:
        type: "constant"
        mean: 10
        std: null
        min: null
        max: null
      type: "random"
  pricing: &pricing
    num_items: 1 
    agents:
      - type: "random"
        count: 1

# SETTINGS FOR EACH REQUIREMENT
req_1:
  <<: *defaults
  auction: 
    <<: *auction
    type: "second_price"
req_2:
  <<: *defaults
  auction:
    <<: *auction
    type: "generalized_first_price"
req_3:
  <<: *defaults
  type: "pricing"
req_3_bonus:
  <<: *defaults
  type: "pricing"
  pricing: 
    <<: *pricing
    num_items: 2
req_4:
  <<: *defaults
  type: "bidding"
  auction:
    <<: *auction
    agents:
      - type: "random"
        count: 4

# Logger
log_path: ".\\logger\\logs\\"